baseURL = "https://dwalkr.github.io/sawmill/"
languageCode = "en-us"
theme = "sawmill"
title = "Sawmill"
[Author]
name = "DJ Walker"
[[menu.main]]
name = "Home"
url = "/"
weight = 11
[params]
logo = "/logo.svg"
title = "Insidemotors"
