---
new_page_extension: md
auto_deploy: true
admin_path: gestor
webhook_url: 
sections: 
upload_dir: ''
public_path: ''
front_matter_path: ''
use_front_matter_path: 
file_template: ":filename:"
version: 0.38.1
